repository:
  name: hyperledger-labs.github.io
  description: Hyperledger Labs
  homepage: https://hyperledger-labs.github.io/
  default_branch: master
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
