repository:
  name: lf-decentralized-trust-labs.github.io
  description: LF Decentralized Trust Labs
  homepage: https://lf-decentralized-trust-labs.github.io
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
